I HAS A VAR
VAR R "HELLO"
VISIBLE VAR
VISIBLE SUM OF VAR AN " WORLD"
VISIBLE DIFF OF 1 AN 1
VISIBLE BOTH SAEM VAR VAR
I HAS A BOOL ITZ WIN
VISIBLE NOT BOOL
VISIBLE BIGGR OF 100 AN 10
I HAS A FLOAT ITZ 2.25
FLOAT IS NOW A TROOF
VISIBLE FLOAT
